service: aws-linuxprofile-api

frameworkVersion: '3'

package:
  individually: true

provider:
  name: aws
  runtime: python3.9

functions:
  app:
    handler: app.main.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    layer:
      name: FastAPI-Lambda-Function
      description: FastAPI-Lambda-Function API Layer
      compatibleRuntimes:
        - python3.9
